export default function page() {
  return 'dynamic page'
}

export async function generateMetadata() {
  const icon = '/home-icon.png'
  return {
    title: 'title',
    description: 'description',
    icons: {
      icon: icon,
      apple: icon,
      shortcut: icon,
    },
    twitter: {
      card: 'summary_large_image',
      site: '@nextjs',
      creator: '@huozhi',
      title: 'Create Next App',
      description: 'Generated by create next app',
    },

  }
}