import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  metadataBase: new URL(process.env.VERCEL_URL ||
    process.env.NODE_ENV === 'production'
      ? 'https://cna-canary-huozhi.vercel.app'
      : 'http://localhost:3000'
  ),
  twitter: {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
